"use client";
import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import TextAnimation from '../../components/elements/TextAnimation';
import { pricingData } from '../../all-content/pricing/PricingData';
import Link from 'next/link';
import { motion } from "framer-motion";
import shapeTitleImg from "../../assets/images/shapes/section-title-tagline-shape-1.png";
import taglineShape from '../../assets/images/shapes/section-title-tagline-shape-1.png';
import { pricingPlansThree } from '../../all-content/process/processData';
const PricingMain = () => {
    return (_jsxs(_Fragment, { children: [_jsxs("section", { className: "pricing-one pricing-page-one", children: [_jsx("div", { className: "pricing-one__shape-1" }), _jsx("div", { className: "pricing-one__shape-2" }), _jsxs("div", { className: "container", children: [_jsxs("div", { className: "section-title text-center sec-title-animation animation-style1", children: [_jsxs("div", { className: "section-title__tagline-box justify-content-center", children: [_jsx("div", { className: "section-title__tagline-shape", children: _jsx("img", { src: shapeTitleImg, alt: "Image" }) }), _jsx("span", { className: "section-title__tagline", children: "Pricing & Plan" })] }), _jsxs("h2", { className: "section-title__title title-animation", children: [_jsx(TextAnimation, { text: 'Time Quick and Easy to' }), _jsx(TextAnimation, { text: 'Transportation' })] })] }), _jsx("div", { className: "row", children: pricingData.map((item) => _jsx(motion.div, { initial: { y: item?.id % 2 === 0 ? 50 : -50, opacity: 0 }, whileInView: { y: 0, opacity: 1 }, transition: {
                                        duration: 0.3 * item?.id || 0.5,
                                        ease: "easeOut"
                                    }, viewport: { amount: 0.5, once: true }, className: "col-xl-4 col-lg-6 col-md-6 wow", children: _jsxs("div", { className: "pricing-one__single", children: [_jsxs("div", { className: "pricing-one__title-box", children: [_jsx("h2", { className: "pricing-one__title", children: item?.title }), _jsx("p", { className: "pricing-one__text", children: item?.description })] }), _jsxs("div", { className: "pricing-one__price-and-icon-box", children: [_jsx("div", { className: "pricing-one__price-box", children: _jsxs("h3", { className: "pricing-one__price", children: ["$", item?.price, " ", _jsx("span", { children: item?.duration }), " "] }) }), _jsx("div", { className: "pricing-one__icon-box", children: _jsx("span", { className: `${item?.icon || "icon-taxi"} ` }) })] }), _jsx("ul", { className: "list-unstyled pricing-one__points", children: item.points.map((point, index) => (_jsxs("li", { children: [_jsx("div", { className: "text", children: _jsx("p", { children: point.label }) }), _jsx("div", { className: "price", children: _jsx("p", { children: point.value }) })] }, index))) }), _jsx("div", { className: "pricing-one__btn-box", children: _jsxs(Link, { href: "/inner/pricing", className: "thm-btn", children: ["Rent Now", _jsx("span", { className: "fas fa-arrow-right" })] }) })] }) }, item?.id)) })] })] }), _jsx("section", { className: "pricing-two pricing-page-two", children: _jsxs("div", { className: "container", children: [_jsxs("div", { className: "section-title text-center sec-title-animation animation-style1", children: [_jsxs("div", { className: "section-title__tagline-box justify-content-center", children: [_jsx("div", { className: "section-title__tagline-shape", children: _jsx("img", { src: taglineShape, alt: "Tagline Shape" }) }), _jsx("span", { className: "section-title__tagline", children: "Pricing & Plan" })] }), _jsxs("h2", { className: "section-title__title title-animation", children: [_jsx(TextAnimation, { text: 'Time Quick and Easy to' }), _jsx(TextAnimation, { text: 'Transportation' })] })] }), _jsx("ul", { className: "list-unstyled pricing-two__list", children: pricingPlansThree.map((plan) => (_jsx("li", { children: _jsxs("div", { className: "pricing-two__single", children: [_jsxs("div", { className: "pricing-two__left-content", children: [_jsx(motion.div, { initial: { x: -80, opacity: 0 }, whileInView: { x: 0, opacity: 1 }, transition: {
                                                        duration: 0.3 * plan?.id,
                                                        ease: "easeOut"
                                                    }, viewport: { amount: 0.01, once: true }, className: "pricing-two__img", children: _jsx("img", { src: plan?.image, alt: plan?.title }) }), _jsxs("div", { className: "pricing-two__img-content", children: [_jsx("h3", { className: "pricing-two__title", children: plan.title }), _jsxs("h2", { className: "pricing-two__price-box", children: ["$", plan.price, " ", _jsx("span", { children: "/Mon" })] })] })] }), _jsxs("div", { className: "pricing-two__right-content", children: [_jsx("ul", { className: "list-unstyled pricing-two__points", children: plan.features.map((feature, index) => (_jsxs("li", { children: [_jsx("div", { className: "icon", children: _jsx("span", { className: "fas fa-check" }) }), _jsx("div", { className: "text", children: _jsx("p", { children: feature }) })] }, index))) }), _jsx("div", { className: "pricing-two__btn-box", children: _jsxs(Link, { href: "/inner/pricing", className: "thm-btn", children: ["Rent Now", _jsx("span", { className: "fas fa-arrow-right" })] }) })] })] }) }, plan.id))) })] }) })] }));
};
export default PricingMain;
