"use client";
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import React from 'react';
import { motion } from "framer-motion";
import tagLine from '../../assets/images/shapes/section-title-tagline-shape-1.png';
import { teamButtonData, teamTabData } from '../../all-content/team/teamData';
import Link from 'next/link';
import TextAnimation from '../../components/elements/TextAnimation';
const TeamOne = () => {
    const [isActiveTab, setIsActiveTab] = React.useState(teamButtonData[0].tabId);
    return (_jsxs("section", { className: "team-one", id: 'driver', children: [_jsx("div", { className: "team-one__shape-1" }), _jsx("div", { className: "team-one__shape-2" }), _jsxs("div", { className: "container", children: [_jsxs("div", { className: "section-title text-center sec-title-animation animation-style1", children: [_jsxs("div", { className: "section-title__tagline-box justify-content-center", children: [_jsx("div", { className: "section-title__tagline-shape", children: _jsx("img", { src: tagLine, alt: "Image" }) }), _jsx("span", { className: "section-title__tagline", children: "Our Drivers" })] }), _jsxs("h2", { className: "section-title__title title-animation", children: [_jsx(TextAnimation, { text: 'Meet Our Premium Drivers' }), " "] })] }), _jsx("div", { className: "team-one__inner", children: _jsx("div", { className: "team-one__main-tab-box tabs-box", children: _jsxs("div", { className: "row", children: [_jsx("div", { className: "col-xl-5 col-lg-5", children: _jsx("div", { className: "team-one__tab-buttons-box-one", children: _jsx("ul", { className: "tab-buttons list-unstyled", children: teamButtonData.map((item) => _jsx(motion.li, { initial: { x: -50, opacity: 0 }, whileInView: { x: 0, opacity: 1 }, transition: {
                                                        duration: 0.3 * item?.id,
                                                        ease: "easeOut"
                                                    }, viewport: { amount: 0.5, once: true }, className: `tab-btn ${isActiveTab === item?.tabId ? 'active-btn' : ''}`, onClick: () => setIsActiveTab(item?.tabId), children: _jsxs("div", { className: "team-one__buttons", children: [_jsxs("div", { className: "team-one__buttons-experience-years", children: [_jsx("div", { className: "team-one__buttons-experience-years-count", children: _jsxs("h3", { children: ["0", item?.experienceYears] }) }), _jsxs("p", { className: "team-one__buttons-experience-years-text", children: ["Years ", _jsx("br", {}), " Experience"] })] }), _jsxs("div", { className: "team-one__buttons-content-box", children: [_jsx("div", { className: "team-one__buttons-img-box", children: _jsx("div", { className: "team-one__buttons-img", children: _jsx("img", { src: item?.image, alt: "Image" }) }) }), _jsx("div", { className: "team-one__buttons-content", children: _jsxs("div", { className: "team-one__buttons-title-box", children: [_jsx("h4", { className: "team-one__buttons-title", children: _jsx(Link, { href: "#", children: item?.name }) }), _jsx("p", { className: "team-one__buttons-sub-title", children: item?.role })] }) })] })] }) }, item?.id)) }) }) }), _jsx("div", { className: "col-xl-7 col-lg-7", children: _jsx("div", { className: "team-one__tabs-content-outer", children: _jsx("div", { className: "tabs-content", children: teamTabData.map((item) => _jsx("div", { className: "tab active-tab", style: { display: `${isActiveTab === `#${item?.tabId}` ? 'block' : 'none'}` }, children: _jsx("div", { className: "team-one__tabs-content-box", children: _jsx("div", { className: "team-one__img-box", children: _jsxs("div", { className: "team-one__img", children: [_jsx("img", { src: item?.image, alt: "Image" }), _jsx("div", { className: "team-one__social", children: item?.socials.map((social, index) => (_jsx(Link, { href: "#", children: _jsx("span", { className: social }) }, index))) })] }) }) }) }, item?.id)) }) }) })] }) }) })] })] }));
};
export default TeamOne;
