"use client";
import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import Link from 'next/link';
import { motion } from "framer-motion";
// section title shape
import sectionTitleShape from "../../assets/images/shapes/section-title-tagline-shape-1.png";
import counterImg1 from "../../assets/images/resources/counter-one-img-1.jpg";
import counterImg2 from "../../assets/images/resources/counter-one-img-2.jpg";
import counterDot1 from "../../assets/images/shapes/counter-one-dot-1.png";
import counterDot2 from "../../assets/images/shapes/counter-one-dot-2.png";
import TextAnimation from "../../components/elements/TextAnimation";
import AdvanceCountUp from "../../components/elements/AdvanceCountUp";
import { counterData, whyChooseData } from "../../all-content/why-choose/chooseData";
const WhychooseOne = () => {
    return (_jsxs(_Fragment, { children: [_jsxs("section", { className: "why-choose-one", children: [_jsx("div", { className: "why-choose-one__shape-1" }), _jsx("div", { className: "why-choose-one__shape-2" }), _jsxs("div", { className: "container", children: [_jsxs("div", { className: "section-title text-center sec-title-animation animation-style2", children: [_jsxs("div", { className: "section-title__tagline-box justify-content-center", children: [_jsx("div", { className: "section-title__tagline-shape", children: _jsx("img", { src: sectionTitleShape, alt: "Image" }) }), _jsx("span", { className: "section-title__tagline", children: "Why Choose Us" })] }), _jsxs("h2", { className: "section-title__title title-animation", children: [_jsx(TextAnimation, { text: "We are innovative and passionate" }), _jsx(TextAnimation, { text: "about the work we do." })] })] }), _jsx("div", { className: "row", children: whyChooseData.map((item, i) => _jsx(motion.div, { className: "col-xl-4 col-lg-6 col-md-6 ", initial: { y: item?.id % 2 === 0 ? 20 : -20, opacity: 0 }, whileInView: { y: 0, opacity: 1 }, transition: {
                                        duration: 0.2 * i + 1,
                                        ease: "easeOut"
                                    }, viewport: { amount: 0.5, once: true }, children: _jsxs("div", { className: "why-choose-one__single", children: [_jsx("div", { className: "why-choose-one__icon", children: _jsx("span", { className: item.icon }) }), _jsxs("div", { className: "why-choose-one__single-inner", children: [_jsx("h3", { className: "why-choose-one__title", children: item.title }), _jsxs("p", { className: "why-choose-one__text", children: [item.text, " "] })] }), _jsx("div", { className: "why-choose-one__btn-box", children: _jsxs(Link, { href: "/inner/listing-single", className: "thm-btn", children: [" Rent Now", _jsx("span", { className: "fas fa-arrow-right" }), " "] }) })] }) }, item?.id)) })] })] }), _jsx("section", { className: "counter-one", children: _jsx("div", { className: "container", children: _jsxs("div", { className: "row", children: [_jsx("div", { className: "col-xl-6", children: _jsxs("div", { className: "counter-one__left", children: [_jsxs("div", { className: "section-title text-left sec-title-animation animation-style1", children: [_jsxs("div", { className: "section-title__tagline-box", children: [_jsx("div", { className: "section-title__tagline-shape", children: _jsx("img", { src: sectionTitleShape, alt: "Image" }) }), _jsx("span", { className: "section-title__tagline", children: "fun facts" })] }), _jsxs("h2", { className: "section-title__title title-animation", children: [_jsx(TextAnimation, { text: "experience freedom on" }), _jsx(TextAnimation, { text: "our car booking service" })] })] }), _jsxs("p", { className: "counter-one__text", children: ["Dominion fowe there light she does lights begining subdue without run saying ", _jsx("br", {}), " moving winger Open multiply a green form lesser"] }), _jsx("div", { className: "counter-one__main-content", children: _jsx("ul", { className: "list-unstyled counter-one__list", children: counterData.map((item, i) => _jsx(motion.li, { initial: { x: item?.id % 2 === 0 ? 30 : -30, opacity: 0 }, whileInView: { x: 0, opacity: 1 }, transition: {
                                                        duration: 0.2 * i + 1,
                                                        ease: "easeOut"
                                                    }, viewport: { amount: 0.01, once: true }, children: _jsxs("div", { className: "counter-one__single", children: [_jsx("div", { className: "counter-one__shape-1" }), _jsx("div", { className: "counter-one__shape-2" }), _jsxs("div", { className: "counter-one__single-inner", children: [_jsx("div", { className: "counter-one__icon", children: _jsx("span", { className: item.icon }) }), _jsxs("div", { className: "counter-one__count-box", children: [_jsx("h3", { className: "odometer", children: _jsx(AdvanceCountUp, { ending: item?.count }) }), _jsx("span", { children: item?.suffix })] }), _jsx("p", { className: "counter-one__count-text", children: item?.text })] })] }) }, item?.id)) }) })] }) }), _jsx("div", { className: "col-xl-6", children: _jsx(motion.div, { initial: { x: 70, opacity: 0 }, whileInView: { x: 0, opacity: 1 }, transition: {
                                        duration: 0.6,
                                        ease: "easeOut"
                                    }, viewport: { amount: 0.01, once: true }, className: "counter-one__right", children: _jsxs("div", { className: "counter-one__img-box", children: [_jsx("div", { className: "counter-one__img ", children: _jsx("img", { src: counterImg1, alt: "Image" }) }), _jsx("div", { className: "counter-one__img-two ", children: _jsx("img", { src: counterImg2, alt: "Image" }) }), _jsx("div", { className: "counter-one__dot-1", children: _jsx("img", { src: counterDot1, alt: "Image" }) }), _jsx("div", { className: "counter-one__dot-2 float-bob-y", children: _jsx("img", { src: counterDot2, alt: "Image" }) })] }) }) })] }) }) })] }));
};
export default WhychooseOne;
