import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import HeaderTwo from '../../sections/home-two/HeaderTwo';
import BannerTwo from '../../sections/home-two/BannerTwo';
import StrickyHeaderTwo from '../../sections/home-two/StrickyHeaderTwo';
import BookingTwo from '../../sections/home-two/BookingTwo';
import AboutTwo from '../../sections/home-two/AboutTwo';
import ServiceTwo from '../../sections/home-two/ServiceTwo';
import SlidingTextOne from '../../sections/home-one/SlidingTextOne';
import ProcessTwo from '../../sections/home-two/ProcessTwo';
import LetsTalk from '../../sections/common/LetsTalk';
import CounterTwo from '../../sections/home-two/CounterTwo';
import ListingTwo from '../../sections/home-two/ListingTwo';
import VideoTwo from '../../sections/home-two/VideoTwo';
import FaqTwo from '../../sections/home-two/FaqTwo';
import ContactTwo from '../../sections/home-two/ContactTwo';
import TeamTwo from '../../sections/home-two/TeamTwo';
import TestimonialTwo from '../../sections/home-two/TestimonialTwo';
import DownloadApp from '../../sections/common/DownloadApp';
import FeatureTwo from '../../sections/home-two/FeatureTwo';
import PopularTwo from '../../sections/home-two/PopularTwo';
import BrandTwo from '../../sections/home-two/BrandTwo';
import Gallery from '../../sections/common/Gallery';
import Footer from '../../sections/common/Footer';
import BlogTwo from '../../sections/home-two/BlogTwo';
const HomeTwo = () => {
    return (_jsxs("div", { className: 'page-wrapper', children: [_jsx(HeaderTwo, {}), _jsx(BannerTwo, {}), _jsx(BookingTwo, {}), _jsx(AboutTwo, {}), _jsx(ServiceTwo, {}), _jsx(SlidingTextOne, {}), _jsx(ProcessTwo, {}), _jsx(LetsTalk, {}), _jsx(CounterTwo, {}), _jsx(ListingTwo, {}), _jsx(VideoTwo, {}), _jsx(FaqTwo, {}), _jsx(ContactTwo, {}), _jsx(TeamTwo, {}), _jsx(TestimonialTwo, {}), _jsx(DownloadApp, {}), _jsx(FeatureTwo, {}), _jsx(PopularTwo, {}), _jsx(BrandTwo, {}), _jsx(BlogTwo, {}), _jsx(Gallery, {}), _jsx(Footer, {}), _jsx(StrickyHeaderTwo, {})] }));
};
export default HomeTwo;
