"use client";
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { motion } from "framer-motion";
import Link from 'next/link';
// Images
import taglineShape from '../../assets/images/shapes/section-title-tagline-shape-1.png';
import aboutImg1 from '../../assets/images/resources/about-three-img-1.jpg';
import aboutImg2 from '../../assets/images/resources/about-three-img-2.jpg';
import aboutImg3 from '../../assets/images/resources/about-three-img-3.jpg';
import AdvanceCountUp from '../../components/elements/AdvanceCountUp';
import TextAnimation from '../../components/elements/TextAnimation';
const AboutThree = () => {
    return (_jsx("section", { className: "about-three", id: 'about', children: _jsx("div", { className: "container", children: _jsxs("div", { className: "row", children: [_jsx("div", { className: "col-xl-6", children: _jsxs(motion.div, { initial: { x: -100, opacity: 0 }, whileInView: { x: 0, opacity: 1 }, transition: {
                                duration: 1.2,
                                ease: "easeOut"
                            }, viewport: { amount: 0.1, once: true }, className: "about-three__left", children: [_jsxs("div", { className: "section-title text-left sec-title-animation animation-style1", children: [_jsxs("div", { className: "section-title__tagline-box", children: [_jsx("div", { className: "section-title__tagline-shape", children: _jsx("img", { src: taglineShape, alt: "Tagline Shape" }) }), _jsx("span", { className: "section-title__tagline", children: "About Gorent" })] }), _jsxs("h2", { className: "section-title__title title-animation", children: [_jsx(TextAnimation, { text: 'Welcome to Gorent' }), _jsx(TextAnimation, { text: 'car booking company' })] })] }), _jsx("p", { className: "about-three__text-1", children: "Lorem ipsum is simply ipun txns mane so dummy text of free available in market the printing and typesetting industry has been the industry's standard dummy text ever." }), _jsxs("div", { className: "about-three__points-box", children: [_jsxs("ul", { className: "list-unstyled about-three__points", children: [_jsxs("li", { children: [_jsx("div", { className: "icon", children: _jsx("span", { className: "icon-car-insurance" }) }), _jsxs("div", { className: "content", children: [_jsx("h3", { children: "Best Car Rental Services" }), _jsx("p", { children: "Vivamus arcu felis bibendum ut tristique et egestas. Ultricies leo intege in malesuada nunc vel risus commodo." })] })] }), _jsxs("li", { children: [_jsx("div", { className: "icon", children: _jsx("span", { className: "icon-range" }) }), _jsxs("div", { className: "content", children: [_jsx("h3", { children: "Easy & Fast Booking" }), _jsx("p", { children: "Vivamus arcu felis bibendum ut tristique et egestas. Ultricies leo intege in malesuada nunc vel risus commodo." })] })] })] }), _jsxs("div", { className: "about-three__btn-box-and-call-box", children: [_jsx("div", { className: "about-three__btn-box", children: _jsxs(Link, { href: "/inner/about", className: "about-three__btn thm-btn", children: ["Read More", _jsx("span", { className: "fas fa-arrow-right" })] }) }), _jsxs("div", { className: "about-three__call-box", children: [_jsx("div", { className: "about-three__call-box-icon", children: _jsx("span", { className: "icon-call-2" }) }), _jsxs("div", { className: "about-three__call-box-content", children: [_jsx("p", { children: "Call to Anytime" }), _jsx("h4", { children: _jsx("a", { href: "tel:15502505260", children: "+1 (550) 250 5260" }) })] })] })] })] })] }) }), _jsx("div", { className: "col-xl-6", children: _jsx(motion.div, { initial: { x: 100, opacity: 0 }, whileInView: { x: 0, opacity: 1 }, transition: {
                                duration: 1.2,
                                ease: "easeOut"
                            }, viewport: { amount: 0.1, once: true }, className: "about-three__right wow slideInRight", children: _jsxs("div", { className: "row", children: [_jsx("div", { className: "col-xl-6 col-lg-6 col-md-6", children: _jsxs("div", { className: "about-three__img-box", children: [_jsx("div", { className: "about-three__img-1", children: _jsx("img", { src: aboutImg1, alt: "About Image 1" }) }), _jsx("div", { className: "about-three__img-2", children: _jsx("img", { src: aboutImg2, alt: "About Image 2" }) })] }) }), _jsx("div", { className: "col-xl-6 col-lg-6 col-md-6", children: _jsxs("div", { className: "about-three__satisfied-and-img", children: [_jsxs("div", { className: "about-three__satisfied-box", children: [_jsx("div", { className: "icon", children: _jsx("span", { className: "icon-reviews" }) }), _jsxs("div", { className: "about-three__count-box", children: [_jsx("div", { className: "about-three__count count-box", children: _jsx("h3", { className: "count-text", children: _jsx(AdvanceCountUp, { ending: 2500 }) }) }), _jsx("p", { className: "about-three__count-text", children: "Satisfied Client" })] })] }), _jsx("div", { className: "about-three__img-3", children: _jsx("img", { src: aboutImg3, alt: "About Image 3" }) })] }) })] }) }) })] }) }) }));
};
export default AboutThree;
